title: Viktor Vidman's site - A Developer’s Learning Journal
description: A documented journey through the ever-evolving world of programming.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile